apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  8443: "akash-services/akash-provider:8443"
  1317: "akash-services/akash-node-1:1317"
  9090: "akash-services/akash-node-1:9090"
  26656: "akash-services/akash-node-1:26656"
  26657: "akash-services/akash-node-1:26657"
  {{- if .Values.bootstrap.enabled }}
  26652: "akash-services/akash-node-2:26656"
  26662: "akash-services/akash-node-2:26657"
  26653: "akash-services/akash-node-3:26656"
  26663: "akash-services/akash-node-3:26657"
  26654: "akash-services/akash-node-4:26656"
  26664: "akash-services/akash-node-4:26657"
  {{- end }}
