apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    helm.sh/chart: ingress-nginx-4.0.1
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
      appProtocol: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
      appProtocol: https
    - name: provider
      port: 8443
      protocol: TCP
    - name: node-api
      port: 1317
      protocol: TCP
    - name: node-grpc
      port: 9090
      protocol: TCP
    - name: node-p2p
      port: 26656
      protocol: TCP
    - name: node-rpc
      port: 26657
      protocol: TCP
    {{- if .Values.bootstrap.enabled }}
    - name: node-2-p2p
      port: 26652
      protocol: TCP
    - name: node-2-rpc
      port: 26662
      protocol: TCP
    - name: node-3-p2p
      port: 26653
      protocol: TCP
    - name: node-3-rpc
      port: 26663
      protocol: TCP
    - name: node-4-p2p
      port: 26654
      protocol: TCP
    - name: node-4-rpc
      port: 26664
      protocol: TCP
    {{- end }}
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller