{{- if .Values.node.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "akash-ingress.fullname" . }}-node-rpc
  namespace: akash-services
  annotations:
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: rpc.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: akash-node-1
                port:
                  number: 26657
{{- end }}
{{- if .Values.bootstrap.enabled }}
{{- range untilStep 1 5 1 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: akash-ingress-node-validator-rpc-{{ . }}
  namespace: akash-services
  annotations:
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: validator-rpc-{{ . }}.{{ $.Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: akash-node-validator-{{ . }}
                port:
                  number: 26657
{{- end }}
{{- end }}
