apiVersion: apps/v1
kind: Deployment
metadata:
  name: akash-ip-operator
  namespace: akash-services
  labels:
    akash.network/component: akash-ip-operator
spec:
  selector:
    matchLabels:
      app: akash-ip-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: akash-ip-operator
        akash.network/component: akash-ip-operator
    spec:
      serviceAccountName: akash-ip-operator
      containers:
      - name: akash-ip-operator
        image: ghcr.io/ovrclk/provider-services:latest
        args: ["provider-services", "ip-operator", "--provider", "{{ .Values.provider_address }}"]
        imagePullPolicy: IfNotPresent
        ports:
          - name: api
            containerPort: 8086
        env:
          - name: AP_K8S_MANIFEST_NS
            value: "lease"
          - name: AP_PRUNE_INTERVAL
            value: "600s"
          - name: AP_IGNORE_LIST_ENTRY_LIMIT
            value: "131072"
          - name: AP_WEB_REFRESH_INTERVAL
            value: "5s"
          - name: AP_RETRY_DELAY
            value: "3s"
          - name: AP_LIST_AGE_LIMIT
            value: "2613600s"
          - name: AP_EVENT_FAILURE_LIMIT
            value: "3"
