# Default values for akash-ip-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ghcr.io/ovrclk/provider-services
  provider_services_tag: 0.1.0-rc11

provider_address: 
