apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Chart.Name }}-amplitude-ingress"
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/upstream-vhost: "api2.amplitude.com"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/rewrite-target: /2/httpapi
    nginx.ingress.kubernetes.io/proxy-ssl-server-name: "on"
    nginx.ingress.kubernetes.io/proxy-ssl-name: "api2.amplitude.com"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "{{ .Values.hostName }}"
    secretName: console-web-staging-akash-network-tls
  rules:
  - host: "{{ .Values.hostName }}"
    http:
      paths:
      - path: /api/collect
        pathType: Exact
        backend:
          service:
            name: amplitude-external
            port:
              number: 443
---
apiVersion: v1
kind: Service
metadata:
  name: amplitude-external
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: api2.amplitude.com
