apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "akash-e2e.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "akash-e2e.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "akash-e2e.fullname" . }}
      {{- include "akash-e2e.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-boot.yaml") . | sha256sum }}
      labels:
        app: {{ include "akash-e2e.fullname" . }}
        {{- include "akash-e2e.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "akash-e2e.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: sacreman/akashnines:latest
          command: ["/bin/bash", "/boot/run.sh"]
          env:
            - name: AKASH_DEBUG
              value: "{{ $.Values.debug }}"
            - name: AKASH_PATH
              value: "/bin/akash"
            - name: AKASH_KEYRING_BACKEND
              value: "test"
            - name: POSTGRES_URL
              value: "postgres://akashnines:password@{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc:5432/akashnines"
            - name: CHAIN_ID
              value: "{{ $.Values.chainid }}"
            - name: RPC_NODE
              value: "{{ $.Values.node }}"
            - name: WALLET_HOME
              value: "/root/.akash"
            - name: GAS_PRICES
              value: "{{ $.Values.gasprices }}"
            - name: GAS
              value: "{{ $.Values.gas }}"
            - name: MINIMUM_UAKT_BALANCE
              value: "{{ $.Values.minuaktbalance }}"
            - name: CRITICAL_PROVIDERS
              value: "{{ $.Values.criticalproviders }}"
            - name: BUCKET_NAME
              value: "none"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: boot
              mountPath: /boot
              readOnly: true
            - name: keys
              mountPath: /boot-keys
              readOnly: true
      volumes:
        - name: boot
          configMap:
            name: {{ include "akash-e2e.fullname" . }}-boot
        - name: keys
          secret:
            secretName: {{ include "akash-e2e.fullname" . }}-keys
