apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-apis-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "140"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "140"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "140"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/large-client-header-buffers: "4 32k"
    nginx.ingress.kubernetes.io/proxy-buffers: "8 16k"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.hostName }}
      http:
        paths:
          - path: /api-mainnet(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: console-api-mainnet-service
                port:
                  name: api-port
          - path: /api-sandbox(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: console-api-sandbox-service
                port:
                  name: api-port
          - path: /api-testnet(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: console-api-testnet-service
                port:
                  name: api-port
          - path: /provider-proxy(?:-mainnet)?(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: provider-proxy-mainnet-service
                port:
                  name: api-port
          - path: /provider-proxy-sandbox(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: provider-proxy-sandbox-service
                port:
                  name: api-port
          - path: /provider-proxy-testnet(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: provider-proxy-testnet-service
                port:
                  name: api-port
  tls:
    - hosts:
        - {{ .Values.hostName }}
      secretName: {{ .Chart.Name }}-{{ .Release.Namespace }}-akash-network-tls
